server:
  port: 8043

eureka:
  client:
    service-url:
      defaultZone: http://user:pwd123@peer1:8761/eureka/,http://user:pwd123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-consumer-movie-feign-hystrix

#Ribbon 配置
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.vic.microserviceconsumermoviefeignhystrix.feign.UserFeignClient: info

management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'