server:
  port: 8013

eureka:
  client:
    service-url:
      defaultZone: http://user:pwd123@peer1:8761/eureka/,http://user:pwd123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-consumer-movie-feign-manual

#Ribbon 配置
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule