server:
  port: 8051

eureka:
  client:
    service-url:
      defaultZone: http://user:pwd123@peer1:8761/eureka/,http://user:pwd123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-hystrix-turbine

#健康检查
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'

#断路器跳闸的最小请求数量
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3

turbine:
  app-config: microservice-consumer-movie-feign-hystrix,microservice-consumer-movie-ribbon-hystrix
  cluster-name-expression: "'default'"

